export const RECEIVE_DEPLOYMENTS = 'RECEIVE_DEPLOYMENTS'
export const RECEIVE_INGRESSES = 'RECEIVE_INGRESSES'
export const RECEIVE_WORKER_NODES = 'RECEIVE_WORKER_NODES'
export const RECEIVE_MASTER_NODES = 'RECEIVE_MASTER_NODES'
export const RECEIVE_PODS = 'RECEIVE_PODS'
export const RECEIVE_SERVICES = 'RECEIVE_SERVICES'


