//Structure
export const RECEIVE_DEPLOYMENTS = 'RECEIVE_DEPLOYMENTS'
export const RECEIVE_INGRESSES = 'RECEIVE_INGRESSES'
export const RECEIVE_NODES = 'RECEIVE_NODES'
export const RECEIVE_PODS = 'RECEIVE_PODS'
export const RECEIVE_SERVICES = 'RECEIVE_SERVICES'

//Metrics
export const RECEIVE_DEFAULT_METRICS = 'RECEIVE_DEFAULT_METRICS'
export const RECEIVE_QUERY = 'RECEIVE_QUERY'
export const RECEIVE_QUERY_RANGE = 'RECEIVE_QUERY_RANGE'
export const FETCH_CPU_NODE = 'FETCH_CPU_NODE'
export const FETCH_MEMORY_NODE = 'FETCH_MEMORY_NODE'
export const RECEIVE_CPU_QUERY_RANGE = 'RECEIVE_CPU_QUERY_RANGE'
export const FETCH_HTTP_REQUEST = 'FETCH_HTTP_REQUEST'
export const FETCH_CPU_CONTAINER = 'FETCH_CPU_CONTAINER'

//Custom
export const CUSTOM_QUERY = 'CUSTOM_QUERY'
export const ALL_PROMQL = 'ALL_PROMQL'
export const HYDRATE_CUSTOM = 'HYDRATE_CUSTOM'
<<<<<<< HEAD
export const DELETE_CUSTOM = 'DELETE_CUSTOM'

//Alerts
export const RECEIVE_ALERTS = 'RECEIVE_ALERTS'
=======
>>>>>>> 09d3d438665afe27459ceb81a5410dbabc5e0d90
